### ISSUE TITLE
How to determine a message has been fully transfered

### ISSUE THREAD

**Issue by slince** [reactphp/socket#106] opened 2017-05-31 16:09 UTC
Hi, 

I have created a server socket;
```php
        $this->socket->on('connection', function(ConnectionInterface $connection){
               $connection->on('data', function($message) {
                   $this->createHandler($message, $connection)->handle($message);
               });
        });
        $this->socket->on('error', function($exception){
            $this->dispatcher->dispatch(new Event(EventStore::SOCKET_ERROR, $this, [
                'exception' => $exception
            ]));
        });
        $this->loop->run();
```
If a socket client send large chunks of data(greater than 65535) to the server. the listener for the event "data" will only get partial content every time.
How to gather all the partial content into a complete message?

**Comment by cboden** [comment] 2017-06-01 18:45
You need to implement a protocol on top of the TCP layer. By design TCP is an open ended stream that sends and receives chunks. HTTP, RFC6455, ZMQ, and STOMP are a few examples. Something simpler might be to try [JSON streaming](https://github.com/clue/php-json-stream)

**Comment by slince** [comment] 2017-06-02 03:39
@cboden  Hi, i have got it.
However when I tried to study how "react / http" caught the http message, the package did not reach my expectations.

You will find the http request body seems to be empty:

![image](https://cloud.githubusercontent.com/assets/3785826/26709802/f998aa60-4787-11e7-8dbd-27fc02818b4d.png)

**Comment by cboden** [comment] 2017-06-04 15:11
ping @WyriHaximus

**Comment by WyriHaximus** [comment] 2017-06-04 16:18
@slince we're working on full PSR-7 support for until then the request section on `react/http` on how streaming the body in works: https://github.com/reactphp/http#request

**Comment by slince** [comment] 2017-06-05 04:59
@WyriHaximus 
Ok.
I think the "connection" event should be emitted when the full http message is caught(includes http header and body). You know that almost every request has a body.

**Comment by WyriHaximus** [comment] 2017-06-05 09:02
>  the full http message is caught(includes http header and body)

And there lies the problem. We also support websockets where the 'body' is never done. Another thing is that if a client sends a huge file buffering that would mean loading it all into memory. And for one request that isn't to much of an issue, it becomes an issue when 10s or 100s of clients do that at the same time. Now`react/http`  `v0.8.0` will bring body parsers in the way you suggest: https://github.com/reactphp/http/issues/120

**Comment by clue** [comment] 2017-06-14 07:23
I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can reopen this :+1:

**Closed by clue** 2017-06-14 07:23 UTC
Labels: question
