### ISSUE TITLE
Removed `full-drain` event from Buffer

### ISSUE THREAD

**Issue by akadlec** [reactphp/socket#81] opened 2017-03-14 12:48 UTC
Hello. I have a small problem after upgrade to latest version of reactphp/socket an event on buffer is missing. In previous version there was event `full-drain`. I use this event to fire handlers after data are completly sent to stream.

So is there some other way how to listen on simillar event? Right now i have patched actual buffer class `React\Stream\Buffer`:

```

    public function handleWrite()
    {
        $error = null;
        set_error_handler(function ($errno, $errstr, $errfile, $errline) use (&$error) {
            $error = array(
                'message' => $errstr,
                'number' => $errno,
                'file' => $errfile,
                'line' => $errline
            );
        });

        $sent = fwrite($this->stream, $this->data);

        restore_error_handler();

        // Only report errors if *nothing* could be sent.
        // Any hard (permanent) error will fail to send any data at all.
        // Sending excessive amounts of data will only flush *some* data and then
        // report a temporary error (EAGAIN) which we do not raise here in order
        // to keep the stream open for further tries to write.
        // Should this turn out to be a permanent error later, it will eventually
        // send *nothing* and we can detect this.
        if ($sent === 0 || $sent === false) {
            if ($error === null) {
                $error = new \RuntimeException('Send failed');
            } else {
                $error = new \ErrorException(
                    $error['message'],
                    0,
                    $error['number'],
                    $error['file'],
                    $error['line']
                );
            }

            $this->emit('error', array(new \RuntimeException('Unable to write to stream: ' . $error->getMessage(), 0, $error)));
            $this->close();

            return;
        }

        $exceeded = isset($this->data[$this->softLimit - 1]);
        $this->data = (string) substr($this->data, $sent);

        // buffer has been above limit and is now below limit
        if ($exceeded && !isset($this->data[$this->softLimit - 1])) {
            $this->emit('drain');
        }

        // buffer is now completely empty => stop trying to write
        if ($this->data === '') {
            // stop waiting for resource to be writable
            if ($this->listening) {
                $this->loop->removeWriteStream($this->stream);
                $this->listening = false;

                $this->emit('full-drain', array($this));
            }

            // buffer is end()ing and now completely empty => close buffer
            if (!$this->writable) {
                $this->close();
            }
        }
    }
```

added `$this->emit('full-drain', array($this));`

**Comment by clue** [comment] 2017-03-14 12:56
Thanks for reporting this!

The `full-drain` event has been removed via https://github.com/reactphp/stream/pull/63 recently.

Can you give us some background (gist?) on what you need this event for? Thanks!

**Comment by akadlec** [comment] 2017-03-14 15:28
So, i'm implementing package [binsoul/net-mqtt-client-react](https://github.com/binsoul/net-mqtt-client-react) and this package create client connection to server: https://github.com/binsoul/net-mqtt-client-react/blob/master/src/ReactMqttClient.php

The flow is:
connect to server - send data (socket:write) - after data transfer finished wait for response

**Comment by akadlec** [comment] 2017-03-14 15:32
I could solve it on my side, but there will be edgecases when transfering data will took too long.

**Comment by clue** [comment] 2017-03-14 17:13
> The flow is:
connect to server - send data (socket:write) - after data transfer finished wait for response

Can you show a very simple gist of this and why this requires a `full-drain` event? It's my understanding that data can be received at *ANY* time, i.e. the `data` event could also be emitted while your buffer is flushing, in case it contains multiple pipelined higher-level "messages".

> […] there will be edgecases when transfering data will took too long.

Care to elaborate?

**Comment by clue** [comment] 2017-04-10 12:12
I'm closing this for now as it hasn't received any input in a while and I believe this has been answered. Please come back with more details if this problem persists and we can reopen this :+1:

**Closed by clue** 2017-04-10 12:12 UTC
Labels: help wanted, question

**Comment by akadlec** [comment] 2019-05-24 06:55
Hi @clue i am back to work on this issue :/ I have upgraded to latest version of reactphp/socket and reactphp/strem but still have no idea how to solve missing event `full-drain`

My example of usage:

```
$this->establishConnection()
	->then(function (Socket\ConnectionInterface $connectionStream) {
	...
	$connectionStream->write($packet);
	...
	$connectionStream->on('full-drain', function () {
		$this->streamListening = FALSE;

		$this->handleSend();
	});
	...
	});
```

In my case, `full-drain` event is used to notify script that all data has been sent (packet) and newly received packet is the right one

**Comment by akadlec** [comment] 2019-05-24 16:43
lets keep it closed, i solved it :)

**Comment by WyriHaximus** [comment] 2019-05-24 17:20
@akadlec for future reference for others, what was the cause of your issue and what was the solution?

**Comment by akadlec** [comment] 2019-05-24 18:24
As was written earlier, my script needed to know when transfer of packet to server was finished. So i solved on my side with easy check, so now i could operate without buffer event
