### ISSUE TITLE
Unix-style sockets - error 11, Resource temporarily unavailable

### ISSUE THREAD

**Issue by maciejmrozinski** [reactphp/socket#82] opened 2017-03-14 14:21 UTC
Hi guys,

If You have a moment pls look at this [comment](https://github.com/php-pm/php-pm/issues/192#issuecomment-286413828) of mine. We tracked a possible issue with unix-style sockets (I merged ready pull request there). You will find there a small example to reproduce the issue.

The issue occurs when using unix socket with a lot of processes trying to connect in the same moment (starting 1 master instance and 100 slaves). Problem does not occur with TCP socket and TCPConnector.

**Comment by clue** [comment] 2017-03-14 14:37
Thanks for your report.

It looks like this is not related to this component at all. Is this the SocketClient that reports this error? If so, this is expected behavior, if your system reports that the resource may temporarily be unavailable. You will likely want to implement some higher-level protocol logic in this such, such as a back-off timer and re-trying etc.

I hope this helps :+1: 

I'm closing this for now, please feel free to come back with more details if this problem persists and we can reopen this :+1:

**Closed by clue** 2017-03-14 14:37 UTC
Labels: question
