### ISSUE TITLE
Catching Otherwise Exception

### ISSUE THREAD

**Issue by rokatto** [reactphp/socket#182] opened 2018-11-14 10:25 UTC
Hi,

I have a problem catching an exception when connection fails.

I'm trying to throw the exception on "otherwise()" on this function:

```php
public function checkMachine()
{
    $loop = Factory::create();
    $connector = new Connector($loop,['timeout'=>$this->timeout]);

    $response = $connector->connect($this->host)
        ->then(
            function (ConnectionInterface $conn) use ($loop) {
                $stdout = fopen('php://stdout', 'wb');
                $conn->pipe(
                    new WritableResourceStream(
                        $stdout,
                        $loop
                    )
                );
                $conn->write("S|1");
                $conn->on('data', function ($chunk) use ($loop) {
                    if ($chunk !== 'OK|PENDING') {
                        throw new MachineConnectException($chunk);
                    }

                    $loop->stop();
                });
            }
        )
        ->otherwise(
            function (\RuntimeException $reason) {
                throw $reason;
            }
        )
    ;

    $loop->run();

    return true;
```
I have tried several ways of throwing the exception but i can't catch it here:

```php
public  function checkStatus(Clinic $clinic = null)
    {
        if (!$clinic) {
            return self::STATUS_NOT_EXISTING_CLINIC;
        }

        if (!$clinic->isCKActive()) {
            return self::STATUS_INACTIVE_CLINIC;
        }
        try {
            $machineResponse = $this->socketConnector->checkMachine();
        } catch (\Exception $e) {
            return self::STATUS_MACHINE_NOT_WORKING;
        } catch (\RuntimeException $e) {
            return self::STATUS_MACHINE_NOT_WORKING;
        }

        return self::STATUS_OK;
    }
```

I can catch exceptions when connection is done, but not when it fails and goes through "otherwise()".
Is it possible to throw such an exception in order to catch it in another place in the code?

Thank you!

**Comment by WyriHaximus** [comment] 2018-11-15 22:12
Try replacing `->otherwise` with `->done()` (without a body). `done` will throw any uncatched errors

**Comment by jsor** [comment] 2018-11-16 09:39
The problem is, that you're mixing synchronous with asynchronous code (`otherwise()` is the async equivalent of `catch`). If only the code inside `checkMachine()` uses the event loop, you can use https://github.com/clue/reactphp-block#await.

```php
function checkMachine()
{
    $loop = Factory::create();
    $connector = new Connector($loop, ['timeout' => $this->timeout]);

    $response = $connector->connect($this->host)
        ->then(
            // ...
        )
        // otherwise() removed!
    ;

    return \Clue\React\Block\await($response, $loop);
}
```

**Comment by clue** [comment] 2018-11-20 15:51
I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can reopen this :+1:

**Closed by clue** 2018-11-20 15:51 UTC
Labels: question
